### ISSUE TITLE
Feature request: Accept attribute value as list

### ISSUE THREAD

**Issue by hongquan** [volfpeter/markyp#5]
This is useful when building HTML, where element often has multiple class name. For example, we can code:

```py
span('', class_=('icon', 'icon-user'))
```

to produce

```html
<span class="icon icon-user"></span>
```

**Comment by volfpeter** [comment]
Hi,

Thanks for the idea - I like it! I will have to check how much it complicates typing and markup generation. I would like to keep markup generation as simple and generic as possible, because this project (`markyp`) is not HTML specific.

If you would be interested in contributing a pull request, feel free to do so. Otherwise I will think about an acceptable solution and implement it.

Note however, that `markyp-html` provides a helper method to work around this issue (see [this module](https://github.com/volfpeter/markyp-html/blob/master/markyp_html/__init__.py)):

```Python
from markyp_html import join

span("", class_=join("icon", "icon-user"))
```

**Comment by volfpeter** [comment]
For the record, I have a solution that seems to be working, but there are still plenty of things to do, including typing updates and testing in `markyp-html` and derived projects.

**Comment by hongquan** [comment]
Thank you, @volfpeter . I didn't know `arkyp-html`'s `join` util. I think it is good enough for a quick solution. I am closing this issue.

**Comment by volfpeter** [comment]
Hi @hongquan 

I hope you will enjoy using these projects. Please let me know if you have any further questions, feature requests, anything.

Unfortunately I simply don't have the time to write a proper readthedocs tutorial... The code is fairly well-documented though, so in general I would advise you to start by having a quick look at the code in the Getting started section of the readme of `markyp`, `markyp-html`, `markyp-bootstrap4`, and `markyp-fontawesome`; then quickly check the modules of these projects (including the main package's `__init__.py`). Utility (or core) code is typically located in the main `__init__.py`.
